services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=://mongo:2701mongodb7
    volumes:
      - ./app:/app  # Montar el código fuente local en el contenedor

volumes:
  mongo_data:
